version: "3.7"

x-default-logging: &default
  {}

x-loki-logging: &loki
  driver: loki
  options:
    loki-url: http://localhost:3100/loki/api/v1/push
    mode: non-blocking
    max-buffer-size: 4m
    loki-retries: "3"

x-log-config: &log-config
  # update this value to *loki if needed to see logs in grafana dashboard.
  <<: *default

services:

  proxy:
    image: bahmniindiadistro/proxy:${PROXY_IMAGE_TAG:?}
    build:
      context: .
      dockerfile: proxy/package/docker/Dockerfile
    volumes:
    # - ${CERTIFICATE_PATH}:/etc/tls
    - "bahmni-patient-images:/home/bahmni/patient_images"
    ports:
      - "80:80"
      - "443:443"
    logging: *log-config

  bahmni-config:
    image: '${CONFIG_IMAGE_NAME:?}:${CONFIG_IMAGE_TAG:?}'
    build:
      context: .
      dockerfile: bahmni-config/package/docker/Dockerfile
    volumes:
      - '${CONFIG_VOLUME:?}:/usr/local/bahmni_config'
    logging: *log-config

  bahmni-lab:
    profiles: ["lab-lite","emr"]
    image: 'bahmni/bahmni-lab:${BAHMNI_LAB_IMAGE_TAG:?}'
    logging: *log-config

  openelis:
    profiles: ["openelis","bahmni-standard","emr"]
    image: 'bahmni/openelis:${OPENELIS_IMAGE_TAG:?[ERROR]}'
    volumes:
      - "${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
      - "bahmni-lab-results:/home/bahmni/uploaded_results"
      - "bahmni-lab-files:/home/bahmni/uploaded-files/elis"
    environment:
      OPENMRS_HOST: ${OPENMRS_HOST}
      OPENMRS_PORT: ${OPENMRS_PORT:?}
      OPENMRS_ATOMFEED_USER: ${OPENMRS_ATOMFEED_USER:?}
      OPENMRS_ATOMFEED_PASSWORD: ${OPENMRS_ATOMFEED_PASSWORD:?}
      OPENELIS_DB_SERVER: ${OPENELIS_DB_SERVER}
    depends_on:
      openelisdb:
        condition: service_healthy
    logging: *log-config

  openelisdb:
    profiles: ["openelis","bahmni-standard","emr"]
    image: 'bahmni/openelis-db:${OPENELIS_DB_IMAGE_TAG:?[ERROR]}'
    volumes:
      - '${OPENELIS_DB_DUMP_PATH}:/resources/db-dump'
      - 'openelisdbdata:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    logging: *log-config   
    
  openmrs:
    profiles: ['emr']
    image: bahmniindiadistro/openmrs:${OPENMRS_IMAGE_TAG}
    environment:
      OMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OMRS_DB_HOSTNAME: ${OPENMRS_DB_HOST:?}
      OMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      OMRS_CREATE_TABLES: ${OPENMRS_DB_CREATE_TABLES}
      OMRS_AUTO_UPDATE_DATABASE: ${OPENMRS_DB_AUTO_UPDATE}
      OMRS_MODULE_WEB_ADMIN: ${OPENMRS_MODULE_WEB_ADMIN}
      # OMRS_DEV_DEBUG_PORT: ${OMRS_DEV_DEBUG_PORT}
      OMRS_JAVA_SERVER_OPTS: ${OMRS_JAVA_SERVER_OPTS}
      OMRS_JAVA_MEMORY_OPTS: ${OMRS_JAVA_MEMORY_OPTS}
      OPENELIS_HOST: ${OPENELIS_HOST:?}
      OPENELIS_PORT: ${OPENELIS_PORT:?}
      OPENELIS_ATOMFEED_USER: ${OPENELIS_ATOMFEED_USER:?}
      OPENELIS_ATOMFEED_PASSWORD: ${OPENELIS_ATOMFEED_PASSWORD:?}
      #Mail config
      SEND_MAIL: ${SEND_MAIL}
      MAIL_TRANSPORT_PROTOCOL: ${MAIL_TRANSPORT_PROTOCOL}
      MAIL_SMTP_HOST: ${MAIL_SMTP_HOST}
      MAIL_SMTP_PORT: ${MAIL_SMTP_PORT}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_SMTP_STARTTLS_ENABLE: ${MAIL_SMTP_STARTTLS_ENABLE}
      MAIL_SMTP_SSL_ENABLE: ${MAIL_SMTP_SSL_ENABLE}
      MAIL_DEBUG: ${MAIL_DEBUG}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      #HIP-OMOD Variables. Refer here https://github.com/BahmniIndiaDistro/openmrs-module-hip/tree/master#docker-setup
      PHONE_NUMBER: ${PHONE_NUMBER:?}
      OMRS_DOCKER_ENV: ${OPENMRS_DOCKER_ENV}
      TZ: ${OPENMRS_TZ:?}
    # ports:
      # - ${OMRS_DEV_DEBUG_PORT}:${OMRS_DEV_DEBUG_PORT}
    volumes:
      # - 'openmrs-data:/openmrs/data/modules'
      - "bahmni-lab-results:/home/bahmni/uploaded_results"
      - '${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro'
      - 'configuration_checksums:/openmrs/data/configuration_checksums'
      - 'bahmni-patient-images:/home/bahmni/patient_images'
      - 'bahmni-document-images:/home/bahmni/document_images'
      - 'bahmni-clinical-forms:/home/bahmni/clinical_forms'
    depends_on:
      - openmrsdb
    logging: *log-config

  openmrsdb:
    image: ${OPENMRS_DB_IMAGE_NAME:?}
    restart: always
    profiles: ["emr"]
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${OPENMRS_DB_NAME:?}
      MYSQL_USER: ${OPENMRS_DB_USERNAME:?}
      MYSQL_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
    ports:
      - '3306:3306'
    volumes:
      - 'openmrsdbdata:/var/lib/mysql'
      - 'configuration_checksums:/configuration_checksums'
    logging: *log-config

  bahmni-web:
    image: infoiplitin/bahmni-iplit-web:${BAHMNI_WEB_IMAGE_TAG:?}
    profiles: ["emr"]
    build:
      context: .
      dockerfile: bahmni-web/package/docker/Dockerfile
    volumes:
      #- "${BAHMNI_APPS_PATH:?}/ui/app/:/usr/local/apache2/htdocs/bahmni"
      #- "${BAHMNI_APPS_PATH:?}/ui/node_modules/@bower_components/:/usr/local/apache2/htdocs/bahmni/components"
      - '${CONFIG_VOLUME:?}:/usr/local/apache2/htdocs/bahmni_config/:ro'
    logging: *log-config

  db:
    container_name: db
    image: postgres:${POSTGRES_IMAGE_TAG:?}
    profiles: ["abdm", "emr"]
    environment:
      - POSTGRES_USER=${HIP_DB_USER:?}
      - POSTGRES_PASSWORD=${HIP_DB_PASSWORD:?}
    ports:
      - "5433:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  rabbitmq:
      image: rabbitmq:${RABBITMQ_IMAGE_TAG:?}
      profiles: ["abdm", "emr"]
      container_name: rabbitmq
      ports:
        - "5672:5672"
  otp:
      image: bahmniindiadistro/otp-service:${OTP_SERVICE_IMAGE_TAG:?}
      profiles: ["abdm", "emr"]
      container_name: otp
      depends_on:
        - db
      environment:
        whitelisted:numbers: ${OTP_WHITELIST_NUMBERS}
        ConnectionStrings:DefaultConnection: Host=${OTP_DB_HOST:?};Port=${OTP_DB_PORT:?};Username=${OTP_DB_USER:?};Password=${OTP_DB_PASSWORD:?};Database=${OTP_DB_NAME:?};

  hiu-db-setup:
      image: bahmniindiadistro/hiu-db:${HIU_DB_INITIALIZER_IMAGE_TAG:?}
      profiles: ["abdm", "emr"]
      container_name: hiu-db-setup
      environment:
        - 'JAVA_TOOL_OPTIONS=-Djdbc.url=${HIU_DB_URL:?} -Djdbc.username=${HIU_DB_USER:?} -Djdbc.password=${HIU_DB_PASSWORD:?} -Djdbc.database=${HIU_DB_NAME:?}'

  hip:
    container_name: hip
    image: bahmniindiadistro/hip:${HIP_IMAGE_TAG:?}
    profiles: ["abdm", "emr"]
    ports:
      - "8000:80"
    depends_on:
      - db
      - otp
      - rabbitmq
    environment:
      Gateway:clientSecret: ${ABDM_GATEWAY_CLIENT_SECRET:?}
      Gateway:clientId: ${ABDM_GATEWAY_CLIENT_ID:?}
      Gateway:url: ${ABDM_GATEWAY_URL:?}
      OpenMrs:url: ${OPENMRS_URL:?}
      OpenMrs:password: ${OPENMRS_PASSWORD:?}
      OpenMrs:phoneNumber: ${PHONE_NUMBER:?}
      Gateway:cmSuffix: ${ABDM_CONSENT_MANAGEMENT_SUFFIX:?}
      OtpService:BaseUrl: ${HIP_OTP_SERVICE_URL:?}
      hip:url: ${HIP_URL:?}
      HEALTH_CHECK_DURATION: ${HIP_OPENMRS_HEALTH_CHECK_DURATION:?}
      Cors:allowedOrigins: ${HIP_CORS_ALLOWED_ORIGIN:?}
      Bahmni:Id: ${HIP_ID:?}
      rabbit:HostName: ${RABBITMQ_HOST:?}
      rabbit:UserName: ${RABBITMQ_USERNAME:?}
      rabbit:Password: ${RABBITMQ_PASSWORD:?}
      ConnectionStrings:DefaultConnection: Host=${HIP_DB_HOST:?};Port=${HIP_DB_PORT:?};Username=${HIP_DB_USER:?};Password=${HIP_DB_PASSWORD:?};Database=${HIP_DB_NAME:?};

  hiu:
    image: bahmniindiadistro/hiu:${HIU_IMAGE_TAG:?}
    profiles: ["abdm", "emr"]
    container_name: hiu
    environment:
      HIU_ID: ${HIU_ID:?}
      HIU_NAME: ${HIU_NAME:?}
      IDENTITY_JWK_URL: ${ABDM_IDENTITY_JWK_URL:?}
      DATA_PUSH_URL: ${HIU_DATA_PUSH_URL:?}
      CONSENT_NOTIFICATION_URL: ${ABDM_CONSENT_NOTIFICATION_URL:?}
      CONSENT_MANAGEMENT_SUFFIX:  ${HIU_ABDM_CONSENT_MANAGEMENT_SUFFIX:?}
      CONSENT_MANAGEMENT_URL: ${ABDM_CONSENT_MANAGEMENT_URL:?}
      DEFAULT_PAGE_SIZE: ${HIU_DEFAULT_PAGE_SIZE:?}
      MAX_PAGE_SIZE: ${HIU_MAX_PAGE_SIZE:?}
      LOCAL_STORAGE_PATH: ${HIU_LOCAL_STORAGE_PATH}
      HIU_CLIENT_ID: ${ABDM_GATEWAY_CLIENT_ID:?}
      HIU_CLIENT_SECRET: ${ABDM_GATEWAY_CLIENT_SECRET:?}
      POSTGRES_HOST: ${HIU_DB_HOST:?}
      POSTGRES_PORT: ${HIU_DB_PORT}
      CONSENT_MANAGER_DB_NAME: ${HIU_DB_NAME:?}
      POSTGRES_USER: ${HIU_DB_USER:?}
      POSTGRES_PASSWORD: ${HIU_DB_PASSWORD:?}
      DB_CONNECTION_POOL_SIZE: ${HIU_DB_CONNECTION_POOL_SIZE:?}
      OFFSET_IN_DAYS: ${HIU_OFFSET_IN_DAYS:?}
      USING_GATEWAY: ${HIU_USING_GATEWAY:?}
      GATEWAY_BASE_URL: ${ABDM_GATEWAY_BASE_URL:?}
      GATEWAY_REQUEST_TIMEOUT: ${HIU_GATEWAY_REQUEST_TIMEOUT:?}
      GATEWAY_JWK_URL: ${ABDM_GATEWAY_JWK_URL:?}
      HFR_AFFINITY_DOMAINS: ${ABDM_HFR_AFFINITY_DOMAINS:?}
      RABBITMQ_HOST: ${HIU_RABBITMQ_HOST:?}
      RABBITMQ_PORT: ${HIU_RABBITMQ_PORT:?}
      RABBITMQ_USERNAME: ${HIU_RABBITMQ_USERNAME:?}
      RABBITMQ_PASSWORD: ${HIU_RABBITMQ_PASSWORD:?}
      MAX_IN_MEMORY_SIZE: ${HIU_MAX_IN_MEMORY_SIZE:?}
      DATA_FLOW_CONSENT_REQUEST_WAIT_TIME: ${HIU_DATA_FLOW_CONSENT_REQUEST_WAIT_TIME:?}
      DATA_FLOW_CONSENT_ARTEFACT_WAIT_TIME: ${HIU_DATA_FLOW_CONSENT_ARTEFACT_WAIT_TIME:?}
      DATA_FLOW_PART_WAIT_TIME: ${HIU_DATA_FLOW_PART_WAIT_TIME:?}
    ports:
      - "9053:8003"

  hiu-ui:
    image: bahmniindiadistro/hiu-ui:${HIU_UI_IMAGE_TAG:?}
    profiles: ["abdm", "emr"]
    container_name: hiu-ui
    environment:
      BACKEND_BASE_URL: ${HIU_BACKEND_BASE_URL:?}
      BASE_NAME: ${HIU_UI_BASE_NAME:?}
      TIMEZONE_OFFSET: ${TIMEZONE_OFFSET:?}
      TITLE: "HIU"
    ports:
      - "5000:5000"

  hip-atomfeed-listener:
    container_name: hip-atomfeed-listener
    image: bahmniindiadistro/hip-atomfeed:${HIP_ATOMFEED_IMAGE_TAG:?}
    profiles: ["abdm", "emr"]
    environment:
      DATABASE_URL: ${HIP_ATOMFEED_DB_URL:?}
      DATABASE_NAME: ${HIP_ATOMFEED_DB_NAME:?}
      DATABASE_USERNAME: ${HIP_DB_USER:?}
      DATABASE_PASSWORD: ${HIP_DB_PASSWORD:?}
      OPENMRS_URL: ${OPENMRS_SESSION_URL:?}
      OPENMRS_ENCOUNTER_FEED_URL: ${OPENMRS_ENCOUNTER_FEED_URL:?}
      OPENMRS_USERNAME: ${OPENMRS_USERNAME:?}
      OPENMRS_PASSWORD: ${OPENMRS_PASSWORD:?}
      HIP_URL: ${HIP_URL:?}
      PHONE_NUMBER: ${PHONE_NUMBER:?}
    depends_on:
      - db

  reports:
    image: bahmni/reports:${REPORTS_IMAGE_TAG:?}
    profiles: [ "reports", "emr" ]
    environment:
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST:?}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OPENMRS_DB_USERNAME: ${MYSQL_ROOT_USERNAME:?}
      OPENMRS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      OPENMRS_HOST: ${OPENMRS_HOST:?}
      OPENMRS_PORT: ${OPENMRS_PORT:?}
      OPENELIS_DB_SERVER: openelisdb
      REPORTS_DB_SERVER: reportsdb
      REPORTS_DB_NAME: ${REPORTS_DB_NAME:?}
      REPORTS_DB_USERNAME: ${REPORTS_DB_USERNAME:?}
      REPORTS_DB_PASSWORD: ${REPORTS_DB_PASSWORD:?}
      ODOO_DB_SERVER: odoodb
      ODOO_DB_USERNAME: ${ODOO_DB_USER:?}
      ODOO_DB_PASSWORD: ${ODOO_DB_PASSWORD:?}
    volumes:
      - '${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro'
    depends_on:
      - reportsdb
      - openmrsdb
      - bahmni-web
    logging: *log-config

  reportsdb:
    image: mysql:5.6
    profiles: ["reports", "emr"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${REPORTS_DB_NAME:?}
      MYSQL_USER: ${REPORTS_DB_USERNAME:?}
      MYSQL_PASSWORD: ${REPORTS_DB_PASSWORD:?}
    logging: *log-config

  patient-documents:
    image: 'bahmni/patient-documents:${PATIENT_DOCUMENTS_TAG:?}'
    ports:
      - '8099:80'
    profiles: ["emr"]
    volumes:
      - 'bahmni-document-images:/usr/share/nginx/html/document_images'
    environment:
      - OPENMRS_HOST=${OPENMRS_HOST:?}
    logging: *log-config

  appointments:
    image: bahmni/appointments:${APPOINTMENTS_IMAGE_TAG:?}
    profiles: ["emr","appointments"]
#    volumes:
#      - "${APPOINTMENTS_PATH:?}/dist/:/usr/local/apache2/htdocs/appointments"

  implementer-interface:
    image: bahmni/implementer-interface:${IMPLEMENTER_INTERFACE_IMAGE_TAG:?}
    profiles: ["emr","implementer-interface"]
    #volumes:
    #  - "${IMPLEMENTER_INTERFACE_CODE_PATH:?}/dist:/usr/local/apache2/htdocs/implementer_interface"
    depends_on:
      - openmrs

  abha-verification:
    image: bahmniindiadistro/abha-verification:${ABHA_VERIFICATION_IMAGE_TAG:?}
    profiles: ["abdm", "emr"]

  odoo:
    profiles: ["odoo","emr"]
    image: 'bahmni/odoo-10:${ODOO_IMAGE_TAG:?[ERROR]}'
    ports:
      - '8069:8069'
    volumes:
      - odooappdata:/var/lib/odoo
      - ${EXTRA_ADDONS_PATH}:/mnt/extra-addons
      # # Uncomment the below volume only when you need to modify existing bahmni-addons. Also make sure to update the .env file variable with odoo-modules github repo cloned path.
      # - ${BAHMNI_ODOO_MODULES_PATH}:/opt/bahmni-erp/bahmni-addons
    depends_on:
      odoodb:
        condition: service_healthy
    environment:
      HOST: odoodb
      USER: ${ODOO_DB_USER}
      PASSWORD: ${ODOO_DB_PASSWORD}
    logging: *log-config

  odoodb:
    profiles: ["odoo","emr"]
    image: 'bahmni/odoo-10-db:${ODOO_DB_IMAGE_TAG:?[ERROR]}'
    ports:
      - '5431:5432'
    volumes:
      - '${ODOO_DB_DUMP_PATH}:/resources/db-dump'
      - 'odoodbdata:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U odoo']
      interval: 10s
      timeout: 5s
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${ODOO_DB_PASSWORD}
      POSTGRES_USER: ${ODOO_DB_USER}
    logging: *log-config

  odoo-connect:
    profiles: ["odoo","emr"]
    image: 'bahmni/odoo-connect:${ODOO_CONNECT_IMAGE_TAG:?[ERROR]}'
    environment:
      ODOO_DB_SERVER: odoodb
      ODOO_DB_USERNAME: ${ODOO_DB_USER:?}
      ODOO_DB_PASSWORD: ${ODOO_DB_PASSWORD:?}
      OPENMRS_HOST: ${OPENMRS_HOST:?}
      OPENMRS_PORT: ${OPENMRS_PORT:?}
      OPENMRS_ATOMFEED_USER: ${OPENMRS_ATOMFEED_USER:?}
      OPENMRS_ATOMFEED_PASSWORD: ${OPENMRS_ATOMFEED_PASSWORD:?}
      OPENELIS_HOST: ${OPENELIS_HOST:?}
      OPENELIS_PORT: ${OPENELIS_PORT:?}
      OPENELIS_ATOMFEED_USER: ${OPENELIS_ATOMFEED_USER:?}
      OPENELIS_ATOMFEED_PASSWORD: ${OPENELIS_ATOMFEED_PASSWORD:?}
      ODOO_HOST: ${ODOO_HOST:?}
      ODOO_PORT: ${ODOO_PORT:?}
      ODOO_ATOMFEED_USER: ${ODOO_ATOMFEED_USER:?}
      ODOO_ATOMFEED_PASSWORD: ${ODOO_ATOMFEED_PASSWORD:?}
    depends_on:
      odoodb:
        condition: service_healthy
    logging: *log-config

  atomfeed-console:
    image: bahmni/atomfeed-console:latest
    profiles: ["atomfeed-console"]
    environment:
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME}
      OPENMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD}
      ODOO_DB_HOST: ${ODOO_DB_HOST}
      ODOO_DB_NAME: ${ODOO_DB_NAME}
      ODOO_DB_USER: ${ODOO_DB_USER}
      ODOO_DB_PASSWORD: ${ODOO_DB_PASSWORD}
      OPENELIS_DB_HOST: ${OPENELIS_DB_HOST}
      OPENELIS_DB_USER: ${OPENELIS_DB_USER}
      OPENELIS_DB_PASSWORD: ${OPENELIS_DB_PASSWORD}
      # PACS_INTEGRATION_DB_HOST: ${PACS_DB_HOST}
      # PACS_INTEGRATION_DB_NAME: ${PACS_INTEGRATION_DB_NAME}
      # PACS_INTEGRATION_DB_USERNAME: ${PACS_INTEGRATION_DB_USERNAME}
      # PACS_INTEGRATION_DB_PASSWORD: ${PACS_INTEGRATION_DB_PASSWORD}

volumes:
  openmrs-data:
  openelisdbdata:
  odoodbdata:
  odooappdata:
  openmrsdbdata:
  bahmni-patient-images:
  bahmni-document-images:
  postgresql:
  postgresql_data:
  bahmni-config:
  configuration_checksums:
  bahmni-clinical-forms:
